// Code generated by MockGen. DO NOT EDIT.
// Source: client/client.go

// Package client is a generated GoMock package.
package client

import (
	reflect "reflect"

	zms "github.com/AthenZ/athenz/clients/go/zms"
	gomock "github.com/golang/mock/gomock"
)

// MockZmsClient is a mock of ZmsClient interface.
type MockZmsClient struct {
	ctrl     *gomock.Controller
	recorder *MockZmsClientMockRecorder
}

// MockZmsClientMockRecorder is the mock recorder for MockZmsClient.
type MockZmsClientMockRecorder struct {
	mock *MockZmsClient
}

// NewMockZmsClient creates a new mock instance.
func NewMockZmsClient(ctrl *gomock.Controller) *MockZmsClient {
	mock := &MockZmsClient{ctrl: ctrl}
	mock.recorder = &MockZmsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockZmsClient) EXPECT() *MockZmsClientMockRecorder {
	return m.recorder
}

// DeleteAssertionPolicyVersion mocks base method.
func (m *MockZmsClient) DeleteAssertionPolicyVersion(domainName, policyName, version string, assertionId int64, auditRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAssertionPolicyVersion", domainName, policyName, version, assertionId, auditRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAssertionPolicyVersion indicates an expected call of DeleteAssertionPolicyVersion.
func (mr *MockZmsClientMockRecorder) DeleteAssertionPolicyVersion(domainName, policyName, version, assertionId, auditRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAssertionPolicyVersion", reflect.TypeOf((*MockZmsClient)(nil).DeleteAssertionPolicyVersion), domainName, policyName, version, assertionId, auditRef)
}

// DeleteGroup mocks base method.
func (m *MockZmsClient) DeleteGroup(domain, groupName, auditRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", domain, groupName, auditRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockZmsClientMockRecorder) DeleteGroup(domain, groupName, auditRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockZmsClient)(nil).DeleteGroup), domain, groupName, auditRef)
}

// DeleteGroupMembership mocks base method.
func (m *MockZmsClient) DeleteGroupMembership(domain, groupName string, member zms.GroupMemberName, auditRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroupMembership", domain, groupName, member, auditRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroupMembership indicates an expected call of DeleteGroupMembership.
func (mr *MockZmsClientMockRecorder) DeleteGroupMembership(domain, groupName, member, auditRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroupMembership", reflect.TypeOf((*MockZmsClient)(nil).DeleteGroupMembership), domain, groupName, member, auditRef)
}

// DeleteMembership mocks base method.
func (m *MockZmsClient) DeleteMembership(domain, roleMember string, member zms.MemberName, auditRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMembership", domain, roleMember, member, auditRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMembership indicates an expected call of DeleteMembership.
func (mr *MockZmsClientMockRecorder) DeleteMembership(domain, roleMember, member, auditRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMembership", reflect.TypeOf((*MockZmsClient)(nil).DeleteMembership), domain, roleMember, member, auditRef)
}

// DeletePolicy mocks base method.
func (m *MockZmsClient) DeletePolicy(domain, policyName, auditRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePolicy", domain, policyName, auditRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePolicy indicates an expected call of DeletePolicy.
func (mr *MockZmsClientMockRecorder) DeletePolicy(domain, policyName, auditRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePolicy", reflect.TypeOf((*MockZmsClient)(nil).DeletePolicy), domain, policyName, auditRef)
}

// DeletePolicyVersion mocks base method.
func (m *MockZmsClient) DeletePolicyVersion(domainName, policyName, version, auditRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePolicyVersion", domainName, policyName, version, auditRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePolicyVersion indicates an expected call of DeletePolicyVersion.
func (mr *MockZmsClientMockRecorder) DeletePolicyVersion(domainName, policyName, version, auditRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePolicyVersion", reflect.TypeOf((*MockZmsClient)(nil).DeletePolicyVersion), domainName, policyName, version, auditRef)
}

// DeleteRole mocks base method.
func (m *MockZmsClient) DeleteRole(domain, roleName, auditRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", domain, roleName, auditRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockZmsClientMockRecorder) DeleteRole(domain, roleName, auditRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockZmsClient)(nil).DeleteRole), domain, roleName, auditRef)
}

// DeleteServiceIdentity mocks base method.
func (m *MockZmsClient) DeleteServiceIdentity(domain, serviceName, auditRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteServiceIdentity", domain, serviceName, auditRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteServiceIdentity indicates an expected call of DeleteServiceIdentity.
func (mr *MockZmsClientMockRecorder) DeleteServiceIdentity(domain, serviceName, auditRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteServiceIdentity", reflect.TypeOf((*MockZmsClient)(nil).DeleteServiceIdentity), domain, serviceName, auditRef)
}

// DeleteSubDomain mocks base method.
func (m *MockZmsClient) DeleteSubDomain(parentDomain, subDomainName, auditRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubDomain", parentDomain, subDomainName, auditRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubDomain indicates an expected call of DeleteSubDomain.
func (mr *MockZmsClientMockRecorder) DeleteSubDomain(parentDomain, subDomainName, auditRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubDomain", reflect.TypeOf((*MockZmsClient)(nil).DeleteSubDomain), parentDomain, subDomainName, auditRef)
}

// DeleteTopLevelDomain mocks base method.
func (m *MockZmsClient) DeleteTopLevelDomain(name, auditRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTopLevelDomain", name, auditRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTopLevelDomain indicates an expected call of DeleteTopLevelDomain.
func (mr *MockZmsClientMockRecorder) DeleteTopLevelDomain(name, auditRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTopLevelDomain", reflect.TypeOf((*MockZmsClient)(nil).DeleteTopLevelDomain), name, auditRef)
}

// DeleteUserDomain mocks base method.
func (m *MockZmsClient) DeleteUserDomain(domainName, auditRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserDomain", domainName, auditRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserDomain indicates an expected call of DeleteUserDomain.
func (mr *MockZmsClientMockRecorder) DeleteUserDomain(domainName, auditRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserDomain", reflect.TypeOf((*MockZmsClient)(nil).DeleteUserDomain), domainName, auditRef)
}

// GetAuditRef mocks base method.
func (m *MockZmsClient) GetAuditRef() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditRef")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuditRef indicates an expected call of GetAuditRef.
func (mr *MockZmsClientMockRecorder) GetAuditRef() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditRef", reflect.TypeOf((*MockZmsClient)(nil).GetAuditRef))
}

// GetDomain mocks base method.
func (m *MockZmsClient) GetDomain(domainName string) (*zms.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDomain", domainName)
	ret0, _ := ret[0].(*zms.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDomain indicates an expected call of GetDomain.
func (mr *MockZmsClientMockRecorder) GetDomain(domainName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDomain", reflect.TypeOf((*MockZmsClient)(nil).GetDomain), domainName)
}

// GetGroup mocks base method.
func (m *MockZmsClient) GetGroup(domain, groupName string, pending *bool) (*zms.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroup", domain, groupName, pending)
	ret0, _ := ret[0].(*zms.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroup indicates an expected call of GetGroup.
func (mr *MockZmsClientMockRecorder) GetGroup(domain, groupName, pending interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroup", reflect.TypeOf((*MockZmsClient)(nil).GetGroup), domain, groupName, pending)
}

// GetGroupMetaResourceState mocks base method.
func (m *MockZmsClient) GetGroupMetaResourceState(groupMetaResourceState, requestedState int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupMetaResourceState", groupMetaResourceState, requestedState)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetGroupMetaResourceState indicates an expected call of GetGroupMetaResourceState.
func (mr *MockZmsClientMockRecorder) GetGroupMetaResourceState(groupMetaResourceState, requestedState interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupMetaResourceState", reflect.TypeOf((*MockZmsClient)(nil).GetGroupMetaResourceState), groupMetaResourceState, requestedState)
}

// GetGroups mocks base method.
func (m *MockZmsClient) GetGroups(domainName string, members *bool) (*zms.Groups, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroups", domainName, members)
	ret0, _ := ret[0].(*zms.Groups)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroups indicates an expected call of GetGroups.
func (mr *MockZmsClientMockRecorder) GetGroups(domainName, members interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroups", reflect.TypeOf((*MockZmsClient)(nil).GetGroups), domainName, members)
}

// GetPolicies mocks base method.
func (m *MockZmsClient) GetPolicies(domainName string, assertions, includeNonActive bool) (*zms.Policies, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicies", domainName, assertions, includeNonActive)
	ret0, _ := ret[0].(*zms.Policies)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicies indicates an expected call of GetPolicies.
func (mr *MockZmsClientMockRecorder) GetPolicies(domainName, assertions, includeNonActive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicies", reflect.TypeOf((*MockZmsClient)(nil).GetPolicies), domainName, assertions, includeNonActive)
}

// GetPolicy mocks base method.
func (m *MockZmsClient) GetPolicy(domain, policy string) (*zms.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicy", domain, policy)
	ret0, _ := ret[0].(*zms.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicy indicates an expected call of GetPolicy.
func (mr *MockZmsClientMockRecorder) GetPolicy(domain, policy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicy", reflect.TypeOf((*MockZmsClient)(nil).GetPolicy), domain, policy)
}

// GetPolicyList mocks base method.
func (m *MockZmsClient) GetPolicyList(domainName string, limit *int32, skip string) (*zms.PolicyList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicyList", domainName, limit, skip)
	ret0, _ := ret[0].(*zms.PolicyList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicyList indicates an expected call of GetPolicyList.
func (mr *MockZmsClientMockRecorder) GetPolicyList(domainName, limit, skip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicyList", reflect.TypeOf((*MockZmsClient)(nil).GetPolicyList), domainName, limit, skip)
}

// GetPolicyVersion mocks base method.
func (m *MockZmsClient) GetPolicyVersion(domainName, policyName, version string) (*zms.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicyVersion", domainName, policyName, version)
	ret0, _ := ret[0].(*zms.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicyVersion indicates an expected call of GetPolicyVersion.
func (mr *MockZmsClientMockRecorder) GetPolicyVersion(domainName, policyName, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicyVersion", reflect.TypeOf((*MockZmsClient)(nil).GetPolicyVersion), domainName, policyName, version)
}

// GetPolicyVersionList mocks base method.
func (m *MockZmsClient) GetPolicyVersionList(domainName, policyName string) (*zms.PolicyList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicyVersionList", domainName, policyName)
	ret0, _ := ret[0].(*zms.PolicyList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicyVersionList indicates an expected call of GetPolicyVersionList.
func (mr *MockZmsClientMockRecorder) GetPolicyVersionList(domainName, policyName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicyVersionList", reflect.TypeOf((*MockZmsClient)(nil).GetPolicyVersionList), domainName, policyName)
}

// GetRole mocks base method.
func (m *MockZmsClient) GetRole(domain, roleName string, expand, pending *bool) (*zms.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", domain, roleName, expand, pending)
	ret0, _ := ret[0].(*zms.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockZmsClientMockRecorder) GetRole(domain, roleName, expand, pending interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockZmsClient)(nil).GetRole), domain, roleName, expand, pending)
}

// GetRoleList mocks base method.
func (m *MockZmsClient) GetRoleList(domainName string, limit *int32, skip string) (*zms.RoleList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleList", domainName, limit, skip)
	ret0, _ := ret[0].(*zms.RoleList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleList indicates an expected call of GetRoleList.
func (mr *MockZmsClientMockRecorder) GetRoleList(domainName, limit, skip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleList", reflect.TypeOf((*MockZmsClient)(nil).GetRoleList), domainName, limit, skip)
}

// GetRoleMetaResourceState mocks base method.
func (m *MockZmsClient) GetRoleMetaResourceState(roleMetaResourceState, requestedState int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleMetaResourceState", roleMetaResourceState, requestedState)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetRoleMetaResourceState indicates an expected call of GetRoleMetaResourceState.
func (mr *MockZmsClientMockRecorder) GetRoleMetaResourceState(roleMetaResourceState, requestedState interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleMetaResourceState", reflect.TypeOf((*MockZmsClient)(nil).GetRoleMetaResourceState), roleMetaResourceState, requestedState)
}

// GetRoles mocks base method.
func (m *MockZmsClient) GetRoles(domainName string, members *bool, tagKey, tagValue string) (*zms.Roles, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoles", domainName, members, tagKey, tagValue)
	ret0, _ := ret[0].(*zms.Roles)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoles indicates an expected call of GetRoles.
func (mr *MockZmsClientMockRecorder) GetRoles(domainName, members, tagKey, tagValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoles", reflect.TypeOf((*MockZmsClient)(nil).GetRoles), domainName, members, tagKey, tagValue)
}

// GetServiceIdentity mocks base method.
func (m *MockZmsClient) GetServiceIdentity(domain, serviceName string) (*zms.ServiceIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceIdentity", domain, serviceName)
	ret0, _ := ret[0].(*zms.ServiceIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceIdentity indicates an expected call of GetServiceIdentity.
func (mr *MockZmsClientMockRecorder) GetServiceIdentity(domain, serviceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceIdentity", reflect.TypeOf((*MockZmsClient)(nil).GetServiceIdentity), domain, serviceName)
}

// GetServiceIdentityList mocks base method.
func (m *MockZmsClient) GetServiceIdentityList(domainName string, limit *int32, skip string) (*zms.ServiceIdentityList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceIdentityList", domainName, limit, skip)
	ret0, _ := ret[0].(*zms.ServiceIdentityList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceIdentityList indicates an expected call of GetServiceIdentityList.
func (mr *MockZmsClientMockRecorder) GetServiceIdentityList(domainName, limit, skip interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceIdentityList", reflect.TypeOf((*MockZmsClient)(nil).GetServiceIdentityList), domainName, limit, skip)
}

// PostSubDomain mocks base method.
func (m *MockZmsClient) PostSubDomain(parentDomain, auditRef string, detail *zms.SubDomain) (*zms.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostSubDomain", parentDomain, auditRef, detail)
	ret0, _ := ret[0].(*zms.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostSubDomain indicates an expected call of PostSubDomain.
func (mr *MockZmsClientMockRecorder) PostSubDomain(parentDomain, auditRef, detail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostSubDomain", reflect.TypeOf((*MockZmsClient)(nil).PostSubDomain), parentDomain, auditRef, detail)
}

// PostTopLevelDomain mocks base method.
func (m *MockZmsClient) PostTopLevelDomain(auditRef string, detail *zms.TopLevelDomain) (*zms.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostTopLevelDomain", auditRef, detail)
	ret0, _ := ret[0].(*zms.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostTopLevelDomain indicates an expected call of PostTopLevelDomain.
func (mr *MockZmsClientMockRecorder) PostTopLevelDomain(auditRef, detail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostTopLevelDomain", reflect.TypeOf((*MockZmsClient)(nil).PostTopLevelDomain), auditRef, detail)
}

// PostUserDomain mocks base method.
func (m *MockZmsClient) PostUserDomain(domainName, auditRef string, detail *zms.UserDomain) (*zms.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostUserDomain", domainName, auditRef, detail)
	ret0, _ := ret[0].(*zms.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostUserDomain indicates an expected call of PostUserDomain.
func (mr *MockZmsClientMockRecorder) PostUserDomain(domainName, auditRef, detail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostUserDomain", reflect.TypeOf((*MockZmsClient)(nil).PostUserDomain), domainName, auditRef, detail)
}

// PutAssertionConditions mocks base method.
func (m *MockZmsClient) PutAssertionConditions(domainName, policyName string, assertionId int64, auditRef string, assertionConditions *zms.AssertionConditions) (*zms.AssertionConditions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutAssertionConditions", domainName, policyName, assertionId, auditRef, assertionConditions)
	ret0, _ := ret[0].(*zms.AssertionConditions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutAssertionConditions indicates an expected call of PutAssertionConditions.
func (mr *MockZmsClientMockRecorder) PutAssertionConditions(domainName, policyName, assertionId, auditRef, assertionConditions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutAssertionConditions", reflect.TypeOf((*MockZmsClient)(nil).PutAssertionConditions), domainName, policyName, assertionId, auditRef, assertionConditions)
}

// PutAssertionPolicyVersion mocks base method.
func (m *MockZmsClient) PutAssertionPolicyVersion(domainName, policyName, version, auditRef string, assertion *zms.Assertion) (*zms.Assertion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutAssertionPolicyVersion", domainName, policyName, version, auditRef, assertion)
	ret0, _ := ret[0].(*zms.Assertion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutAssertionPolicyVersion indicates an expected call of PutAssertionPolicyVersion.
func (mr *MockZmsClientMockRecorder) PutAssertionPolicyVersion(domainName, policyName, version, auditRef, assertion interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutAssertionPolicyVersion", reflect.TypeOf((*MockZmsClient)(nil).PutAssertionPolicyVersion), domainName, policyName, version, auditRef, assertion)
}

// PutDomainMeta mocks base method.
func (m *MockZmsClient) PutDomainMeta(name, auditRef string, detail *zms.DomainMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutDomainMeta", name, auditRef, detail)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutDomainMeta indicates an expected call of PutDomainMeta.
func (mr *MockZmsClientMockRecorder) PutDomainMeta(name, auditRef, detail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutDomainMeta", reflect.TypeOf((*MockZmsClient)(nil).PutDomainMeta), name, auditRef, detail)
}

// PutGroup mocks base method.
func (m *MockZmsClient) PutGroup(domain, groupName, auditRef string, group *zms.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutGroup", domain, groupName, auditRef, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutGroup indicates an expected call of PutGroup.
func (mr *MockZmsClientMockRecorder) PutGroup(domain, groupName, auditRef, group interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutGroup", reflect.TypeOf((*MockZmsClient)(nil).PutGroup), domain, groupName, auditRef, group)
}

// PutGroupMembership mocks base method.
func (m *MockZmsClient) PutGroupMembership(domain, groupName string, memberName zms.GroupMemberName, auditRef string, membership *zms.GroupMembership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutGroupMembership", domain, groupName, memberName, auditRef, membership)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutGroupMembership indicates an expected call of PutGroupMembership.
func (mr *MockZmsClientMockRecorder) PutGroupMembership(domain, groupName, memberName, auditRef, membership interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutGroupMembership", reflect.TypeOf((*MockZmsClient)(nil).PutGroupMembership), domain, groupName, memberName, auditRef, membership)
}

// PutGroupMeta mocks base method.
func (m *MockZmsClient) PutGroupMeta(domain, groupName, auditRef string, group *zms.GroupMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutGroupMeta", domain, groupName, auditRef, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutGroupMeta indicates an expected call of PutGroupMeta.
func (mr *MockZmsClientMockRecorder) PutGroupMeta(domain, groupName, auditRef, group interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutGroupMeta", reflect.TypeOf((*MockZmsClient)(nil).PutGroupMeta), domain, groupName, auditRef, group)
}

// PutMembership mocks base method.
func (m *MockZmsClient) PutMembership(domain, roleName string, memberName zms.MemberName, auditRef string, membership *zms.Membership) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutMembership", domain, roleName, memberName, auditRef, membership)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutMembership indicates an expected call of PutMembership.
func (mr *MockZmsClientMockRecorder) PutMembership(domain, roleName, memberName, auditRef, membership interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutMembership", reflect.TypeOf((*MockZmsClient)(nil).PutMembership), domain, roleName, memberName, auditRef, membership)
}

// PutPolicy mocks base method.
func (m *MockZmsClient) PutPolicy(domain, policyName, auditRef string, policy *zms.Policy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutPolicy", domain, policyName, auditRef, policy)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutPolicy indicates an expected call of PutPolicy.
func (mr *MockZmsClientMockRecorder) PutPolicy(domain, policyName, auditRef, policy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutPolicy", reflect.TypeOf((*MockZmsClient)(nil).PutPolicy), domain, policyName, auditRef, policy)
}

// PutPolicyVersion mocks base method.
func (m *MockZmsClient) PutPolicyVersion(domainName, policyName string, policyOptions *zms.PolicyOptions, auditRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutPolicyVersion", domainName, policyName, policyOptions, auditRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutPolicyVersion indicates an expected call of PutPolicyVersion.
func (mr *MockZmsClientMockRecorder) PutPolicyVersion(domainName, policyName, policyOptions, auditRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutPolicyVersion", reflect.TypeOf((*MockZmsClient)(nil).PutPolicyVersion), domainName, policyName, policyOptions, auditRef)
}

// PutRole mocks base method.
func (m *MockZmsClient) PutRole(domain, roleName, auditRef string, role *zms.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutRole", domain, roleName, auditRef, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutRole indicates an expected call of PutRole.
func (mr *MockZmsClientMockRecorder) PutRole(domain, roleName, auditRef, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutRole", reflect.TypeOf((*MockZmsClient)(nil).PutRole), domain, roleName, auditRef, role)
}

// PutRoleMeta mocks base method.
func (m *MockZmsClient) PutRoleMeta(domain, roleName, auditRef string, group *zms.RoleMeta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutRoleMeta", domain, roleName, auditRef, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutRoleMeta indicates an expected call of PutRoleMeta.
func (mr *MockZmsClientMockRecorder) PutRoleMeta(domain, roleName, auditRef, group interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutRoleMeta", reflect.TypeOf((*MockZmsClient)(nil).PutRoleMeta), domain, roleName, auditRef, group)
}

// PutServiceIdentity mocks base method.
func (m *MockZmsClient) PutServiceIdentity(domain, serviceName, auditRef string, detail *zms.ServiceIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutServiceIdentity", domain, serviceName, auditRef, detail)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutServiceIdentity indicates an expected call of PutServiceIdentity.
func (mr *MockZmsClientMockRecorder) PutServiceIdentity(domain, serviceName, auditRef, detail interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutServiceIdentity", reflect.TypeOf((*MockZmsClient)(nil).PutServiceIdentity), domain, serviceName, auditRef, detail)
}

// SetActivePolicyVersion mocks base method.
func (m *MockZmsClient) SetActivePolicyVersion(domainName, policyName string, policyOptions *zms.PolicyOptions, auditRef string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActivePolicyVersion", domainName, policyName, policyOptions, auditRef)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActivePolicyVersion indicates an expected call of SetActivePolicyVersion.
func (mr *MockZmsClientMockRecorder) SetActivePolicyVersion(domainName, policyName, policyOptions, auditRef interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActivePolicyVersion", reflect.TypeOf((*MockZmsClient)(nil).SetActivePolicyVersion), domainName, policyName, policyOptions, auditRef)
}
