# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

shared:
  image: vespaengine/vespa-build-centos7:latest
  settings:
    email:
      addresses: [athenz@yahooinc.com]
      statuses: [SUCCESS, FAILURE]
  environment:
    USER_SHELL_BIN: bash
  annotations:
    screwdriver.cd/cpu: 8
    screwdriver.cd/ram: 16
    screwdriver.cd/disk: HIGH
    screwdriver.cd/timeout: 120
    screwdriver.cd/dockerEnabled: true
    screwdriver.cd/dockerCpu: HIGH
    screwdriver.cd/dockerRam: HIGH  

parameters:
  upgrade_test: 
    value: "true"
    description: "upgrade test is needed when non-breaking schema changes are applied"
  
jobs:
  certify-provider:
    environment:
      USER_SHELL_BIN: bash
    secrets:
      - SD_DEPLOY_KEY
    steps:
      - install-deps: |
          ./scripts/goupdate.sh
          set -e
          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          yum -y install wget docker-ce-cli
          docker system info
          ls -la $SD_DIND_SHARE_PATH
      - tag-prerelease-version: |
          ./scripts/git-tag.sh -r prerelease -t true
      - run-tests-prerelease-version: |
          UPGRADE_TEST=$(meta get parameters.upgrade_test.value)
          echo "Perform upgrade test case: $UPGRADE_TEST"
          PRERELEASE_VERSION=$(meta get git.version)
          PREVIOUS_VERSION=$(meta get git.prev.version)
          echo "PRERELEASE_VERSION: $PRERELEASE_VERSION"
          echo "PREVIOUS_VERSION: $PREVIOUS_VERSION"
          if [[ "$UPGRADE_TEST" == "true" ]]; then
            echo "about to perform upgrade test using previous version: $PREVIOUS_VERSION"
            ./execution/sys-test.sh "$PREVIOUS_VERSION"
          fi
          ./scripts/wait-for-prerelease-version.sh "$PRERELEASE_VERSION"
          ./execution/sys-test.sh "$PRERELEASE_VERSION" "$UPGRADE_TEST"
      - tag-certify-version: |
          ./scripts/git-tag.sh -r patch -t true

  pull-request:
    requires: [~pr]
    secrets:
      - SD_DEPLOY_KEY
    steps:
      - install-deps: |
          ./scripts/goupdate.sh
          set -e
          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          yum -y install wget docker-ce-cli
          docker system info
          ls -la $SD_DIND_SHARE_PATH
      - unit-test: |
          make unit
          ./execution/pr-acc-test.sh
