# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

shared:
  image: vespaengine/vespa-build-centos7:latest
  settings:
    email:
      addresses: [athenz@yahooinc.com]
      statuses: [SUCCESS, FAILURE]
  environment:
    USER_SHELL_BIN: bash

jobs:
  pull-request:
    annotations:
      screwdriver.cd/cpu: 8
      screwdriver.cd/ram: 16
      screwdriver.cd/disk: HIGH
      screwdriver.cd/timeout: 120
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: HIGH
      screwdriver.cd/dockerRam: HIGH
    requires: [~commit]
    environment:
      USER_SHELL_BIN: bash
    steps:
      - install-deps: |
          set -e
          sd-cmd exec docker/install@latest
          docker system info
      - run-tests: |
          ./sys-test.sh
