# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

shared:
  image: vespaengine/vespa-build-centos7:latest
  settings:
    email:
      addresses: [athenz@yahooinc.com]
      statuses: [SUCCESS, FAILURE]
  environment:
    USER_SHELL_BIN: bash

jobs:
  certify-provider:
    annotations:
      screwdriver.cd/cpu: 8
      screwdriver.cd/ram: 16
      screwdriver.cd/disk: HIGH
      screwdriver.cd/timeout: 120
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/dockerCpu: HIGH
      screwdriver.cd/dockerRam: HIGH
    requires: [~commit]
    environment:
      USER_SHELL_BIN: bash
    secrets:
      - SD_DEPLOY_KEY
    steps:
      - install-deps: |
          set -e
          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          yum -y install wget docker-ce-cli
          docker system info
          ls -la $SD_DIND_SHARE_PATH
      - tag-prerelease-version: |
          ./git-tag.sh -r prerelease -t true
      - run-tests-prerelease-version: |
          PRERELEASE_VERSION=$(meta get git.version)
          ./provider-version-update.sh $PRERELEASE_VERSION
          ./sys-test.sh
      - tag-certify-version: |
          ./git-tag.sh -r patch -t true

  pull-request:
    requires: [~pr]
    secrets:
      - SD_DEPLOY_KEY
    steps:
      - unit-test: |
          make unit
